stages:
  - Devdeploy
Devdeploy:
  environment: DEV
  stage: Devdeploy
  image: maven:3.6.3-ibmjava-8-alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:

    - echo "Deploy to development Server"
    - "cd /var/lib/jenkins/workspace/backoffice && git pull origin master && mvn install -Pmaster && mvn tomcat:undeploy -Pmaster && mvn tomcat:redeploy -Pmaster"
    #- mvn clean install
    #- mvn sonar:sonar -Dsonar.projectKey=java -Dsonar.host.url=http://78.47.89.165:9000 -Dsonar.login=dc567dee92bf33383f69158bf0f9778ab769d61e -Dsonar.java.binaries=target/classes
  only:
    - master
